### ISSUE TITLE
Question pre merging

### ISSUE THREAD

**Issue by zolaemil** [aerhard/MEItoVexFlow#2]
Hi Alex,
I'm about to merge your changes back to the main branch. The following three tests are failing:
- overrides with specifications in <staffDef> if present
- overrides with specifications in <scoreDef> if not present in <staffDef>
- overrides with specifications in <scoreDef> if <staffDef> is undefined

I'm not too worried about these bugs, just want to know if you are aware of them?

I also added some minor fixes and pushed them to a branch within the main repo (https://github.com/TEI-Music-SIG/MEItoVexFlow/commit/4ed218719f8d4e31516ecc987d6c40300f96f987) 
and created a pull request from there: https://github.com/TEI-Music-SIG/MEItoVexFlow/pull/67
Cheers
Zoltan

**Comment by raffazizzi** [comment]
@zolaemil thanks for taking care of this! :)

**Comment by aerhard** [comment]
Thanks! There was an issue in the test -- I made a PR fixing it
